-- Extend the persisted skill orchestration surface.
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'COMPANY_INTELLIGENCE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SEO_AUDIT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'GEO_AUDIT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'AUDIENCE_ANALYSIS';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CONTENT_AUDIT';

ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'AI_CMO';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'TECHNICAL_SEO';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'COMPETITOR';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'AUDIENCE';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'CONTENT_AUDIT';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'CAMPAIGN_PLANNER';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'INSTAGRAM';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'YOUTUBE';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'CREATIVE_VISUAL';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'UGC_INFLUENCER';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'EMAIL_NEWSLETTER';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'PAID_MEDIA';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'COMMUNITY';

ALTER TABLE "User"
ADD COLUMN "tokenBudget" INTEGER NOT NULL DEFAULT 2000000,
ADD COLUMN "tokenUsed" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Document"
ADD COLUMN "skillProvenance" JSONB,
ADD COLUMN "tokenEstimate" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "AgentRun"
ADD COLUMN "sources" JSONB,
ADD COLUMN "skills" JSONB,
ADD COLUMN "confidence" INTEGER,
ADD COLUMN "tokensUsed" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE "DocumentVersion" (
    "id" TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "contentMarkdown" TEXT NOT NULL,
    "editPrompt" TEXT,
    "editMode" TEXT NOT NULL DEFAULT 'focused',
    "tokenEstimate" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DocumentVersion_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "DocumentVersion_documentId_version_key" ON "DocumentVersion"("documentId", "version");
CREATE INDEX "DocumentVersion_documentId_createdAt_idx" ON "DocumentVersion"("documentId", "createdAt");

ALTER TABLE "DocumentVersion"
ADD CONSTRAINT "DocumentVersion_documentId_fkey"
FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;
